### ISSUE TITLE
Could you please do releases?

### ISSUE THREAD

**Issue by darix** [anthwlock/untrunc#100]
There are already packages for the software and releases would make the life of a packager easier.

Thank you in advance.

**Comment by anthwlock** [comment]
> short rev makes it more readable sure but it is still not sortable

What about `echo "v$(git rev-list --count HEAD)-$(git describe --always --dirty --abbrev=7)"` ?

> as it wont trigger e.g. the release logic from github e.g. and packager and also websites which do release tracking work on real tags

I would like to know what exactly you are trying to do (which service(s) are you using?), because maybe there are more elegant solutions. I don't like the idea of giving each commit its own tag, that's (IMHO) not what tags are for. But that's what I see end up happening, because the development currently just consists of little changes each now and then.

> just do simple ints as version numbers like systemd.

But these would still have to be made manually, right?

**Comment by darix** [comment]
do you guarantee that every commit is something a normal end user should use or can it happen that you will need a few commits to get it right?

that's basically what it boils down to. and basically almost all distributions have the rule "ship releases".

**Comment by anthwlock** [comment]
> do you guarantee that every commit is something a normal end user should use or can it happen that you will need a few commits to get it right?

Not necessarily every commit, but for every push.

> and basically almost all distributions have the rule "ship releases".

Yes, and I also think that is a good thing for bigger projects. But if what ends up happening is "always tag after push", I don't see much of a benefit. Of course if your build system can only catch up on new git tags, I can see how using them would help. That's why I asked which (build/trigger) service/mechanism you are using.

The same issue occurred when starting to integrate snapcraft releases (#54), as it features different release [channels](https://snapcraft.io/docs/channels), for which I just didn't see the use for in this project.

**Comment by nwparker** [comment]
You could do builds when a PR is merged into the master branch (if you use PRs). Github actions should let you set up this hook easy enough. Example:

```yaml
on:
  # Trigger the workflow on PR on master branch
  pull_request:
    branches:
      - master
```

**Comment by anthwlock** [comment]
> Github actions

This looks promising.

However I am still not fully convinced that creating a new release on every push would be the right thing to do.
I understand that it could potentially make the packaging process easier for certain build systems, but I yet have to see a concrete example. Maybe if someone could point me to a concrete case, that would convince me.

As I see it, currently the packager can simply create a sortable version tag like this:
`echo "v$(git rev-list --count HEAD)-$(git describe --always --dirty --abbrev=7)"`

**Comment by anthwlock** [comment]
In 3d11955f71e21af30940b58a06cc1ecb0bfe276c I made `untrunc -V` use the 'v\<N\>-\<commit\>' version scheme (where N := number of commits).

I will close this for now, since the discussion seems to have stalled

**Comment by milahu** [comment]
> N := number of commits

this breaks with shallow clones

```
$ untrunc --version
version '' using ffmpeg '9.0' Lavc63.1.100
```

workaround: patch VER in Makefile
example: [untrunc.nix](https://github.com/milahu/nur-packages/blob/0ef19b5f8cd33e04236dda37a80dd4f83d5ee6c5/pkgs/by-name/untrunc/package.nix#L31)

also, force-pushing the tag `latest` on every commit is bad practice
if at all, `latest` should be a branch, not a tag

> N := number of commits

please do

```
git log --reverse --format=%H | grep -n . | while IFS=: read N H; do git tag v$N $H; done
git push --tags
```
