### ISSUE TITLE
I love you

### ISSUE THREAD

**Issue by weirdalsuperfan** [anthwlock/untrunc#106]
The windows GUI worked and instantly got me back all hour and 45 minutes of a video I'd thought was gone forever.

Also appreciate the install with snap option on ubuntu (had to do apt-get install snapd first, though...but I backtracked after I noticed there was a GUI with a smaller footprint than snap)

That is all.

**Comment by bridadan** [comment]
Rather than opening up another issue, I figured I'd add my thanks to this one. This fixed an hour long audio recording I had taken of my grandparent sharing some stories from their younger years, priceless stuff! Really appreciate your work here, I used the Dockerfile on Arch Linux and worked first try, thanks again!
