### ISSUE TITLE
Cannot fix the file

### ISSUE THREAD

**Issue by enterjoke** [anthwlock/untrunc#26]
I am definitely not a tech guru and I am definitely new to coding. I really got fixated upon the issue of fixing the broken file in .m4a format. Its size is very small, about 20MB and yeah, I really did my best. 

I tried installing VirtualBox just to emulate Linux Ubuntu and used ponchio's instructions but every time I got to compiling step I would stumble upon the problem of not having config.h file. When I used your instructions, the problem disappeared. But another one came up after - Linux cannot open .m4a files and cannot fix it. 

So yeah, I just tried to use your instruction on macOS which I am using, but never got any success as Terminal doesn't understand the commands that are in your Building instructions. What am I to do? 

It's been almost two days of me trying everything. I tried various libav libraries, tried to translate the linux terminal language to macos terminal language. Updated YASM and so on. i don't know what to do and I am totally frustrated...

**Comment by anthwlock** [comment]
> Linux cannot open .m4a files and cannot fix it.

What makes you think that?  You might have to install additional codecs/packages.. But if you use e.g. the vlc player, it should work out of the box.

> [macOS] Terminal doesn't understand the commands

I guess because the required build tools are not installed?

There are actually automated windows [builds](https://github.com/anthwlock/untrunc/releases) of this fork.
Let me know if it helps, and if not add untruncs output here. It would be extra helpful if you'd upload the files you are using.
