### ISSUE TITLE
Assertion failed error

### ISSUE THREAD

**Issue by ComradDart** [anthwlock/untrunc#35]
![image](https://user-images.githubusercontent.com/8507587/66716021-2a1c6400-ee0d-11e9-942d-4dea3bb83fdd.png)
Get this error, reference video is 100% ok and playable.

Win10x64

**Comment by anthwlock** [comment]
Please try the newest version, I recently fixed some bugs related to this.
If this does not help, and you don't want to send me the files, try to use the '-k' option.

**Comment by ComradDart** [comment]
Ok, I'll try it a bit later. Also I can send you files, if you don't mind

**Comment by ComradDart** [comment]
![image](https://user-images.githubusercontent.com/8507587/66728344-920f9080-ee87-11e9-83c5-a4315bc52ba5.png)
So now I've got this. How can I send you files?

**Comment by anthwlock** [comment]
Just send me the link via email!
If you look for a place to upload the files, I believe [wetransfer](https://wetransfer.com/) is ok.

**Comment by ComradDart** [comment]
E-mailed you so, thanks

**Comment by anthwlock** [comment]
The file `bad.MP4` is a zero-length file!
This means it contains no data at all, and thus no recovery is possible :(

I [added](https://github.com/anthwlock/untrunc/commit/a4396615b24cb7f66659c901892ae50e993500cc) a corresponding error message.

**Comment by tab328** [comment]
I've got the same error except "Line 476" on any files over ~300MB

**Comment by anthwlock** [comment]
@tab328 
Again, I need the files (healthy + broken) in order to figure out what the problem is.

**Comment by tab328** [comment]
Nevermind, problem solved. Turns out you need free space equivalent to the size of the healthy and broken files, or just a 1-2gb overhead on the drive you're saving to. Moved everything to a larger volume and it's working perfectly. I should've known too, the whole problem started because the volume I was downloading to filled before the stream finished and couldn't terminate properly...

That said, thank you for the quick response and many more thanks for the windows gui!
