### ISSUE TITLE
Core dumped after Assertion `track.offsets_.back() < mdat->start_ + mdat->length_' failed

### ISSUE THREAD

**Issue by Lotus907efi** [anthwlock/untrunc#39]
Info: version '51ebdc1-dirty' using ffmpeg 'N-95906-g2952d9c'
Info: reading /media/cdrom/backup/Videos/dessert.mp4
Info: parsing healthy moov atom ... 
Composition time offset atom found. Out of order samples possible.
Sample dependency flag atom found. I and P frames might need to recover that info.
untrunc: src/mp4.cpp:117: void Mp4::parseTracksOk(): Assertion `track.offsets_.back() < mdat->start_ + mdat->length_' failed.
Aborted (core dumped)

**Comment by anthwlock** [comment]
Interesting! Please send me the files (healthy+broken) to the email mentioned on my [profile](https://github.com/anthwlock).
For uploading you can use [wetransfer](https://wetransfer.com/).

**Comment by Lotus907efi** [comment]
OK, but these are XXX films. You OK with that?

**Comment by anthwlock** [comment]
yes, as long as it contains nothing illegal

**Comment by anthwlock** [comment]
For some reason your files contain two mdat atoms, the first one containing nothing but itself.
untrunc now skips such mdat atoms.
However, it probably would still fail if the first one wasn't empty. But since I have no such file, I cant test it further.

Will close this soon if you don't report any further problems/bugs.

**Comment by Lotus907efi** [comment]
So I should re-pull source from git and try it again?

**Comment by anthwlock** [comment]
sounds reasonable.
