### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by 4dvn** [anthwlock/untrunc#46]
Can you upload the source of windows gui? I wanna add more function

**Comment by anthwlock** [comment]
https://github.com/anthwlock/untrunc/tree/master/src/gui

What do you want to add?

**Comment by 4dvn** [comment]
> https://github.com/anthwlock/untrunc/tree/master/src/gui
> 
> What do you want to add?

I have some infected video files by ransomware is encrypted the 150kb of header and 334 bytes of the end of files need to recover:
[video.zip](https://github.com/anthwlock/untrunc/files/4466873/video.zip)

**Comment by anthwlock** [comment]
I still don't understand what function you want to add.

The latest commit I added (23490c6) should be helpful in your case.
I think it removed some of the audio noise at the beginning.
Btw, you know about `-s`, right?

**Comment by 4dvn** [comment]
> I still don't understand what function you want to add.
> 
> The latest commit I added ([23490c6](https://github.com/anthwlock/untrunc/commit/23490c6bb4746698ca9aba4900a4a3d950c1297e)) should be helpful in your case.
> I think it removed some of the audio noise at the beginning.
> Btw, you know about `-s`, right?

Oh is -sm option from gui missing

**Comment by anthwlock** [comment]
I added a `-range` option, it is used like this:
`untrunc -s -range 725000:-350000 good.mov bad.mov`

Additionally I noticed that the original `trak` atom seems to be fully contained in the `.mado` file.
You can take advantage of this:
`untrunc -range 32: -u bad.mov bad.mov`

> Oh is -sm option from gui missing

It probably won't find the start of the `mdat`atom, since the first ~150kb are encrypted.

> can you add repair all corrupt files on the folder and output repaired save file with original name without *-fixed

Hmm.. why not just write a little script?

**Comment by 4dvn** [comment]
> I added a `-range` option, it is used like this:
> `untrunc -s -range 725000:-350000 good.mov bad.mov`
> 
> Additionally I noticed that the original `trak` atom seems to be fully contained in the `.mado` file.
> You can take advantage of this:
> `untrunc -range 32: -u bad.mov bad.mov`
> 
> > Oh is -sm option from gui missing
> 
> It probably won't find the start of the `mdat`atom, since the first ~150kb are encrypted.
> 
> > can you add repair all corrupt files on the folder and output repaired save file with original name without *-fixed
> 
> Hmm.. why not just write a little script?

Can you tell the way to compile it on windows? I can't find to recompile source code 😭

**Comment by anthwlock** [comment]
The [windows build](https://github.com/anthwlock/untrunc/releases) is updated automatically.

**Comment by 4dvn** [comment]
i got error on line 230 of mp4 file on mp4.cpp

**Comment by anthwlock** [comment]
This means that the file you provided as second argument has no `moov` atom.
Please check with a hexeditor.

Maybe that file is from a different camera? If the `moov` atom comes before the `mdat` atom, it will probably be contained in the first 150kb, and thus get encrypted.
Nikon also adds a (relatively)  large `udta` (~385KB) atom at the end, which further "protects" the `moov` atom, since the file end also gets encrypted.
Though in the case where only the last 334 bytes get encrypted, this shouldn't matter.

Have you tried: `untrunc -s -range 725000:-350000 good.mov bad.mov`?

**Comment by DRCRecoveryData** [comment]
> This means that the file you provided as second argument has no `moov` atom. Please check with a hexeditor.
> 
> Maybe that file is from a different camera? If the `moov` atom comes before the `mdat` atom, it will probably be contained in the first 150kb, and thus get encrypted. Nikon also adds a (relatively) large `udta` (~385KB) atom at the end, which further "protects" the `moov` atom, since the file end also gets encrypted. Though in the case where only the last 334 bytes get encrypted, this shouldn't matter.
> 
> Have you tried: `untrunc -s -range 725000:-350000 good.mov bad.mov`?

is encrypted extractly 153605 bytes by default from header
