### ISSUE TITLE
Stuttery video in QuickTime Player

### ISSUE THREAD

**Issue by cbenhagen** [anthwlock/untrunc#59]
I get a stuttery result when playing back in QuickTime Player. It looks like a key frame keeps getting repeated in between regular frames. Playing back in ffplay and VLC works normally. `ffmpeg -c copy` does not help.

Here is a sample: https://we.tl/t-hsqhlZeGYs

Hopefully the stuttery repaired version can be used to provide a working moov for testing? I currently don't have access to a better sample.

Maybe related to #56

**Comment by anthwlock** [comment]
Does the QuickTime Player output any logs?
How often does it occur? When does it occur in the sample you provided?

> Do you have access to a macOS machine? Maybe I can provide a screen recording.

I don't, but QuickTime is available for win7 too, isn't it?
A screen recording would surely be useful. 

> Unfortunately I can't provide a bigger sample as it is not my footage.

What about a working reference file?

**Comment by cbenhagen** [comment]
@anthwlock this shows another repaired example and a rendering from quicktime which should show what happens:
https://we.tl/t-AXLNUOJMDA

I will send you a working reference file by email.

**Comment by cbenhagen** [comment]
@sentience does this example look similar to yours from #56? (The link has expired)

**Comment by sentience** [comment]
@cbenhagen Yes, that looks similar, if not identical to the results I was getting with my broken video.

**Comment by anthwlock** [comment]
I think the stuttering is caused by the removal of the [ctts](https://www.gdcl.co.uk/mpeg4/ctts.htm) atom.
Please try the [restore_ctts](https://github.com/anthwlock/untrunc/commits/restore_ctts) branch.

In case of @cbenhagen's files the ctts values can be guessed easily.
In @sentience's files they are more complicated.. see `untrunc -d`, last column.

But I don't think that this is the cause for out-of-sync audio/video (mentioned in #56), since the composition time offsets don't accumulate. Compare [stts](https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFChap2/qtff2.html#//apple_ref/doc/uid/TP40000939-CH204-BBCGFJII) and [ctts](https://developer.apple.com/library/archive/documentation/QuickTime/QTFF/QTFFChap2/qtff2.html#//apple_ref/doc/uid/TP40000939-CH204-SW19).

**Comment by cbenhagen** [comment]
@anthwlock thanks, the results from the `restore_ctts` branch work as expected in the QuickTime player.

**Comment by denis-sumin** [comment]
Hi! Want to reopen this issue. I have a fix result which plays well in VLC and stops for a frame every ~2.7 seconds in QuickTime and other players in macOS (Preview, Elmedia). Even a recoding with FFmpeg somehow doesn't solve the issue.

Here are one could download my samples: https://yadi.sk/d/tmFwogwpEKiq1g?w=1
Files:
- ok.MP4
- broken.mp4
- fix-result.MP4 obtained from the first 2 with the `-sv` file enabled.

Tried two commits: `8024f0c` (current `master`) and `bab18ae` (branch `restore_ctts`), the results look the same.

**Comment by anthwlock** [comment]
> I have a fix result which plays well in VLC and stops for a frame every ~2.7 seconds in QuickTime and other players in macOS

Are you sure these stops are not present when using the VLC Player? Because I also get them with VLC.
It also looks like your files dont contain the ctts atom, so I think it would be better to open a new issue (instead of reopening).
If you do, please provide a longer healthy reference file. It would be interesting to know if `good.mp4_fixed.mp4` (the file produced by `untrunc good.mp4 good.mp4` also has these stops.
